### ISSUE TITLE
Contact - FetchAll - throws undefined

### ISSUE THREAD

**Issue by dax70** [131/icloud-api#2]
It seems that **url** is not required/imported in https://github.com/131/icloud-api/blob/master/lib/services/contact/index.js in line 29.

``` javascript
   var query = merge(url.parse(contact_url), {
      qs : params,
    });
```

Causing _Uncaught ReferenceError: url is not defined(…)_, when I tried using the contact.fetchAll function.

I took a quick look, so it's possible I may have missed something. Glad to submit a pull request if that's the issue.

**Comment by 131** [comment]
It's seems this is a dummy typo, you got it !

**Comment by dax70** [comment]
OK, great! Submitted a PR.

**Comment by 131** [comment]
Thx a lot
